import { AnimatePresence, motion } from 'framer-motion'
import { Check, Copy, Download, Quote, RefreshCw, Sparkles, TriangleAlert } from 'lucide-react'
import { useState } from 'react'

import { PROJECT } from '../../config/site.js'
import useClipboard from '../../hooks/useClipboard.js'
import { downloadTextFile, stripExtension } from '../../lib/download.js'
import { formatBytes, formatConfidence } from '../../lib/validation.js'
import Button from '../ui/Button.jsx'
import { DemoModePill, Note } from '../ui/DemoNotice.jsx'

/** Generated caption card with copy / regenerate / download actions. */
export default function CaptionResult({ result, file, isBusy, isDemo, onRegenerate }) {
  const { status, copy } = useClipboard()
  const [downloaded, setDownloaded] = useState(false)

  if (!result) return null

  const copyStates = {
    idle: { label: 'Copy Caption', Icon: Copy, className: '' },
    copied: { label: 'Copied', Icon: Check, className: 'text-emerald-300' },
    failed: { label: 'Copy blocked', Icon: TriangleAlert, className: 'text-amber-300' },
  }
  const copyState = copyStates[status]
  const copyAnnouncement =
    status === 'copied'
      ? 'Caption copied to clipboard.'
      : status === 'failed'
        ? 'Clipboard access was blocked. Select the caption text to copy it manually.'
        : ''

  const handleDownload = () => {
    const lines = [
      `${PROJECT.name} — Generated Caption`,
      '='.repeat(46),
      '',
      `Caption     : ${result.caption}`,
      `Confidence  : ${formatConfidence(result.confidence)}`,
      result.scene ? `Scene       : ${result.scene}` : null,
      result.objects?.length ? `Objects     : ${result.objects.join(', ')}` : null,
      file ? `Source file : ${file.name} (${formatBytes(file.size)})` : null,
      `Generated   : ${new Date().toISOString()}`,
      `Source      : ${isDemo ? 'Demo Mode (sample output)' : PROJECT.name + ' model API'}`,
      '',
      '---',
      `Generated by ${PROJECT.name} v${PROJECT.version} · ${PROJECT.author}`,
    ].filter((line) => line !== null)

    downloadTextFile(`${stripExtension(file?.name)}-caption.txt`, lines.join('\n'))
    setDownloaded(true)
    setTimeout(() => setDownloaded(false), 2200)
  }

  return (
    <motion.section
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.55, ease: [0.16, 1, 0.3, 1] }}
      aria-labelledby="caption-result-heading"
      className="relative flex flex-col gap-5 overflow-hidden rounded-[1.4rem] border border-brand-400/22 bg-gradient-to-br from-brand-500/10 via-violet-500/6 to-transparent p-5 sm:p-6"
    >
      <span
        aria-hidden="true"
        className="pointer-events-none absolute -top-24 -right-16 size-56 rounded-full bg-brand-500/18 blur-3xl"
      />

      <div className="relative flex flex-wrap items-center justify-between gap-3">
        <h3
          id="caption-result-heading"
          className="flex items-center gap-2 font-display text-[1.05rem] font-semibold text-ink"
        >
          <Sparkles className="size-4 text-violet-soft" aria-hidden="true" />
          Generated Caption
        </h3>
        <div className="flex items-center gap-2">
          {result.latencyMs ? (
            <span className="font-mono text-[0.68rem] tracking-wide text-subtle">
              {result.latencyMs} ms
            </span>
          ) : null}
          {isDemo && <DemoModePill />}
        </div>
      </div>

      <blockquote className="relative flex gap-3.5 rounded-2xl border border-white/10 bg-void/45 p-4 sm:p-5">
        <Quote
          className="size-5 shrink-0 rotate-180 text-violet-400/60"
          aria-hidden="true"
        />
        <p className="font-display text-[1.15rem] leading-relaxed font-medium text-ink sm:text-[1.28rem]">
          {result.caption}
        </p>
      </blockquote>

      {isDemo && (
        <Note tone="warn">
          This caption is a <strong>sample response</strong> served by Demo Mode because no AI
          backend is configured. Set <code className="font-mono">VITE_API_BASE_URL</code> to connect a
          real FastAPI model service.
        </Note>
      )}

      <div className="flex flex-wrap items-center gap-2.5">
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={onRegenerate}
          disabled={isBusy}
        >
          <RefreshCw className={`size-3.5 ${isBusy ? 'animate-spin' : ''}`} aria-hidden="true" />
          Regenerate
        </Button>

        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => copy(result.caption)}
          disabled={isBusy}
          title={
            status === 'failed'
              ? 'Clipboard access was blocked — select the caption text to copy it manually.'
              : undefined
          }
        >
          <AnimatePresence mode="wait" initial={false}>
            <motion.span
              key={status}
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.8 }}
              className={`flex items-center gap-1.5 ${copyState.className}`}
            >
              <copyState.Icon className="size-3.5" aria-hidden="true" />
              {copyState.label}
            </motion.span>
          </AnimatePresence>
        </Button>

        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={handleDownload}
          disabled={isBusy}
        >
          {downloaded ? (
            <Check className="size-3.5 text-emerald-300" aria-hidden="true" />
          ) : (
            <Download className="size-3.5" aria-hidden="true" />
          )}
          {downloaded ? 'Saved' : 'Download'}
        </Button>
      </div>

      {/* Screen-reader announcements for the transient action feedback. */}
      <p role="status" aria-live="polite" className="sr-only">
        {copyAnnouncement}
        {downloaded ? 'Caption file downloaded.' : ''}
      </p>
    </motion.section>
  )
}
