"""Pydantic response models.

This is the contract the React frontend consumes (see
`src/services/captionService.js`). Only `caption` is required; every other
field is optional so the UI can hide what a model did not actually produce
instead of inventing values.
"""

from pydantic import BaseModel, Field


class CaptionResponse(BaseModel):
    """Successful caption result."""

    caption: str = Field(
        ..., description="Natural-language description generated by the model."
    )
    confidence: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description=(
            "Squashed length-normalised beam score from the decoder. This is a "
            "relative confidence signal, NOT a calibrated probability."
        ),
    )
    objects: list[str] = Field(
        default_factory=list,
        description="Top ImageNet-1k labels above the configured threshold.",
    )
    scene: str | None = Field(
        default=None,
        description="Coarse scene label derived from the predicted object labels.",
    )
    latency_ms: int = Field(
        ..., description="Server-side processing time in milliseconds."
    )
    model: str = Field(..., description="Caption model identifier.")
    source: str = Field("model", description="Always 'model' for live inference.")


class HealthResponse(BaseModel):
    """Service health / readiness probe."""

    status: str
    device: str
    models_loaded: bool
    caption_model: str
    classifier_model: str


class ErrorResponse(BaseModel):
    """Uniform error body."""

    detail: str
